### ISSUE TITLE
It appears that Cosbench does not properly close driver sockets.

### ISSUE THREAD

**Issue by ywang19** [intel-cloud/cosbench#275]
For some reason (Sometimes, not always!) despite kernel settings the kernel fails to recycle disconnected sockets too (I guess this is because of java garbage collector does not destroy the local socket objects). At some point the server ends up with 28717 sockets it CLOSE_WAIT state and fails to create any additional connection, the driver is marked offline and the story stops there.

**Comment by mratner** [comment]
I've been constantly experiencing this issue with 0.4.2.c2 and the latest 0.4.2.0, on both RHEL 7.1 and Ubuntu 14.04. In my case, the number of connections in CLOSE_WAIT state would gradually increase, in increments of 4, up to a little over 4000, at which point the java process runs out of open file descriptor limit (4096) and throws scores of "java.net.SocketException: Too many open files" errors into libs.log file. After that there is some kind of reset and the same process happens again.

Sounds like this can severely impact the test results... IMHO this issue is pretty critical. Is there anything I can try? I'm willing to experiment with it in my local Eclipse instance... would appreciate any pointers.

**Comment by ywang19** [comment]
What storage system you are experimenting?

**Comment by mratner** [comment]
Hitachi Content Platform object store ([Hitachi Content Platform Fundamentals] (https://www.hds.com/assets/pdf/hitachi-white-paper-introduction-to-object-storage-and-hcp.pdf)) using Amazon S3 interface. I also need to mention that this issue occurs in a idle state, i.e. when no test is running, right after I [re]start COSBench processes.

**Comment by ywang19** [comment]
Thanks for the clue. But really quite strange to see the increase on CLOSE_WAIT even at idle, will look at it.

Thanks,
-yaguang

**Comment by ywang19** [comment]
see upcoming 0.4.2.c3 for fixing.

**Comment by mratner** [comment]
Hi Yaguang,

Just wondering - this issue was closed but I haven't seen any fix for it.  0.4.2.c3 doesn't seem to contain any commits pertaining to this problem.

I presume you weren't able to reproduce the issue in your environment?  If so, could you please confirm and also let me know  what environment you tested it in - perhaps I can try this too.

As I mentioned earlier, I'm experiencing the issue in two different scenarios (RHEL 7.1 and Ubuntu Ubuntu 14.04), with identical symptoms and very consistently (happening all the time), so I'm very curious as to what you have to say about this.

Thanks,
-Michael

**Comment by ywang19** [comment]
Hi Michael,

This is an issue caused by heartbeat, previous logic doesn’t close socket, also some logic errors, and #279 is also related to the issue.

Below commits are for the fix:

-      https://github.com/intel-cloud/cosbench/commit/f2e2b70ca775b39854921250814cfd33137c43fd

-      https://github.com/intel-cloud/cosbench/commit/999777e5a7f372ee03dba5bc02611b09bd2a2db7

regards,
-yaguang

**Comment by mratner** [comment]
Awesome, thanks. Just to confirm - the fixes were pushed to 0.4.2.0,  0.4.2.c3 doesn't include them, correct?

**Comment by ywang19** [comment]
The fixes were pushed to 0.4.2.0 branch, and 0.4.2.c3 exactly included them☺.

**Comment by mratner** [comment]
Sorry...I was looking at the 0.4.2.c3 **tag** that didn't show any commits, just as 0.4.2.c3 **source** didn't include any updates. I can see now that the actual **build** zip is updated. This is confusing but I guess that's only because I'm new to GitHub... I'll learn :-)
Going to test the new build now... thanks!

**Comment by mratner** [comment]
Confirming - the issue I've seen before is gone.

**Comment by ywang19** [comment]
Cool! Thanks for your confirmation.
